### ISSUE TITLE
Water level seems too high

### ISSUE THREAD

**Issue by Paul-kingtiger** [KSP-64k/64k#11]
On testing the scaled space maps I've found an issue with the water level.  It seems to be too high which causes low level areas in stock to be under water in 64K.  This adds a bunch of lakes and lagoons around the coast and also causes a lot of water/land Z fighting.  This is really apparent when you look at the scaled space maps (stick something on the pad and then press M).

I'm not sure how we can change the water level using Kopernicus, but we can't really create new scaled space maps until we sort it out or we'll have a water world.  I've kept the new scaled space maps in the current version so you can see what I mean, but once we fix the water level I'll create new maps.

**Comment by Felger** [comment]
I'm not sure either, have a look at NathanKell's RealSolarSystem Kopernicus config for some guidance:
https://github.com/KSP-RO/RealSolarSystem/blob/master/GameData/RealSolarSystem/RSSKopernicus.cfg

**Comment by Paul-kingtiger** [comment]
Fixed this by adjusting PQS settings.
