### ISSUE TITLE
Atmosphere does not load

### ISSUE THREAD

**Issue by Raptor831** [KSP-64k/64k#13]
Seems to be an error for me with the latest Kopernicus and the latest dev release of 64k. Game loads fine, but when the space center is loaded, the sky is black in day and night. Log shows this:

[Kopernicus]: Patching AFG Laythe
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/MacStandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

[Kopernicus]: ERROR AtmosphereFixer => Couldn't patch AtmosphereFromGround for Laythe!
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/MacStandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

[Kopernicus]: Patching AFG Jool
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/MacStandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

[Kopernicus]: ERROR AtmosphereFixer => Couldn't patch AtmosphereFromGround for Jool!
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/MacStandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

[Kopernicus]: Patching AFG Duna
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/MacStandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

[Kopernicus]: ERROR AtmosphereFixer => Couldn't patch AtmosphereFromGround for Duna!
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/MacStandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

[Kopernicus]: Patching AFG Kerbin
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/MacStandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

[Kopernicus]: Patching AFG Eve
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/MacStandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

[Kopernicus]: ERROR AtmosphereFixer => Couldn't patch AtmosphereFromGround for Eve!
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/MacStandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

[Kopernicus]: Patching AFG Kerbin
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/MacStandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

[Kopernicus]: ERROR AtmosphereFixer => Material-resetting for AtmosphereFromGround on Kerbin failed!
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/MacStandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

Kopernicus is installed from CKAN, if that makes any difference. I'll try and do some tweaking to maybe find the issue.

**Comment by Paul-kingtiger** [comment]
I can't recreate this.  I had similar issues with a much earlier version of Kopernicus, but not with 0.8 or 0.9.

**Comment by Raptor831** [comment]
It's the AtmosphereFromGround node in Kerbin's config. If I remove that it loads properly. As usual, I have an absurd amount of mods, so it could be a simple conflict with a mod. I'll do some more testing on my end.

If you want the full logs, let me know and I'll post them up somewhere. I might also take this to the Kopernicus thread, since it might have more to do with that then the 64K config (which otherwise seems just fine).

**Comment by Raptor831** [comment]
Tested this with the latest Kopernicus and 64K as of today, and this problem doesn't happen. Must have been something with my mods or versions.
