### ISSUE TITLE
Installation PDF is wrong

### ISSUE THREAD

**Issue by Felger** [KSP-64k/64k#7]
Completely forgot to remove the install PDF, oh well, install is pretty simple now.

**Comment by Paul-kingtiger** [comment]
I’ve been playing with this all morning and so far no bugs or crashes.

 

Remote tech isn’t creating the extra ground stations that you really need for the larger planet so I’ll fix that.  I assume we aren’t having extra space centers in this release?

 

I think we need to include Kopernicus and Module Manager though, for people who aren’t installing from CKAN.  But we can write the CKAN file so it doesn’t use our versions of those mods but picks them up from their CKAN repository.  That’s what I do with universal storage and it works really well.  We don’t have to update every time a new version of MM or Kopernicus comes out unless it’s to fix a bug our users are having.

 

I’ll update the instructions and license files as well, to make sure they are up to date.

 

Finally, I’m going to push out K2 as well, but was going to change the name to KScale2 so it’s more descriptive and people do get confused with the K2 command pod mod.  How do you feel about changing the name here to KScale6-4.  If we do change it, now is the time as this is the first KSP 1.0.x version and with the new back end.

 

 

Paul Kingtiger

 <http://www.kingtiger.co.uk> www.kingtiger.co.uk

**Comment by Felger** [comment]
The only ground station I'd add is one downrange of the space center for launches, don't want to obviate the need for a space network.  Also, if you don't want RemoteTech to remove control of your unmanned craft just create a MM config like so:  

    @PART[*]:FINAL
    {
    	!MODULE[ModuleSPU] {}
    }

RemoteTech won't recognize them as probes that require a link for control.  You will still have to set up a network for data transmission purposes though.

That's a good point on the Kopernicus and ModuleManager files, it doesn't change the CKAN files, so that's all good.  I'll update the release package with those.

**Comment by Felger** [comment]
For release, been tracking down a bug all day, turns out it's with my config somewhere. Very weird, certain contracts cause the game to freeze.  Will be ironing out the config, should probably hold off on release for a bit.

**Comment by Paul-kingtiger** [comment]
Yeah that’s cool, I want to polish up the documentation anyway.

Let me know when it’s ready on your end.

 

Paul Kingtiger

 <http://www.kingtiger.co.uk> www.kingtiger.co.uk

**Comment by Felger** [comment]
All righty, everything should be good to go for release, I'm going to be out for most of this evening, so I'll load the zip as a pre-release, with some basic text.  When you're ready, edit the text, change the name so it lines up with K2 (might want to change the CKAN package text and resubmit)

Also, might not be a bad idea to run some testing on this version and make sure there are no issues.

**Comment by Felger** [comment]
Scratch that, issue still exists, will troubleshoot later, feel free to poke through the PQS Modifications at the end (all exist in Finalize{}) to see if you can identify the issue, otherwise I'll troubleshoot it later.

**Comment by Felger** [comment]
Hmm, on further investigation, it may be an incompatibility with Contract Configurator.  Testing a bit more.

**Comment by Felger** [comment]
@Paul-kingtiger, I'm currently helping get RO polished and ready to go for release, if you have time, can you do some testing with this most recent release, verify if the "game freezes when you exit the atmosphere or reach orbit in career mode" bug still exists? If not, go ahead and press with release.  If it does, perhaps check the PQS and ScaledSpace settings.

**Comment by Paul-kingtiger** [comment]
Will do.  I've been working on customer site for the past few days but back home today and can devote some proper time to this.Has the contract issue been resolved?
I'd like to cut a new scaled space texture as well so it matched the new terrain.  I believe Kopunicus 0.7 supports this.

Kind regards,Paul Kingtigerpaul.kingtiger@outlook.comwww.kingtiger.co.uk
Please note, my current email address is paul.kingtiger@outlook.com however older emails addresses redirect here, so I will receive your email.

Date: Thu, 11 Jun 2015 07:06:30 -0700

**Comment by Felger** [comment]
I'm unsure if the contract thing is the true source, it might be the scaled
space model (didn't adjust it at all in my builds).

**Comment by Felger** [comment]
More importantly, I replicated the issue after removing Contract
Configurator, and starting a fresh save to remove any traces of its impact
on the game.

**Comment by Paul-kingtiger** [comment]
Been testing this morning and haven't found any issues.
I'm going to update the documentation and release today.

**Comment by Felger** [comment]
Awesome! Did you manage to get some scaled space configs set up?

**Comment by Paul-kingtiger** [comment]
New installation and licence included.
